import { chromium } from 'playwright';
const [w = 1440, h = 900, out = '/tmp/bot'] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: +w, height: +h } });
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.goto('http://127.0.0.1:4173/?snap');
await page.waitForFunction(() => /loaded/.test(document.documentElement.className), null, { timeout: 120000 });
const clickChip = async (text) => { await page.locator('.bot-actions .chip', { hasText: text }).first().click(); await page.waitForTimeout(150); };
await page.locator('[data-book]:visible').first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}-1.png` });
await clickChip('Book an appointment');
await clickChip('Dental implants');
await clickChip('My parent');
await clickChip('Tomorrow');
await clickChip('Evening');
await page.fill('#bot-input', 'A');
await page.click('.bot-form button');
await page.waitForTimeout(150);
await page.screenshot({ path: `${out}-2.png` });
await page.fill('#bot-input', 'Gul Bibi');
await page.click('.bot-form button'); await page.waitForTimeout(150);
await page.fill('#bot-input', '0300 1234567');
await page.click('.bot-form button'); await page.waitForTimeout(150);
await clickChip('Skip');
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}-3.png` });
const href = await page.locator('.bot-actions a.chip.primary').getAttribute('href');
console.log(decodeURIComponent(href));
// question flow
await clickChip('Start again');
await page.locator('.bot-close').click();
await page.locator('[data-book]:visible').first().click();
console.log(errs.join('\n') || 'no page errors');
await browser.close();
