// Content for the treatment pages. One entry = one page, built from the same template
// (tools/treatment-page.mjs). To add a treatment page, add an entry here and rebuild.
//
// Fields marked `confirm: true` list things the clinic should confirm before launch
// (for example which types of a treatment it offers). Medical wording should be checked
// by Dr. Tabassum before the site goes live.

export const TX_GROUPS = {
  pain: 'Pain or damage',
  missing: 'Missing teeth',
  smile: 'Smile makeover',
};

export const TREATMENTS = [
  {
    id: 'implant',
    slug: 'dental-implants',
    tagline: 'Replace a missing tooth',
    name: 'Dental implants',
    group: 'missing',
    scene: 'implant',
    seoTitle: 'Dental implants in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Replace a missing tooth with a dental implant at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar. See how an implant works, step by step, and book on WhatsApp.',
    lead: 'An implant replaces the root of a missing tooth with a small titanium post. Once the bone has healed around it, a crown made for your mouth is fixed on top, so the new tooth looks and works like your own.',
    // Its own seven-step 3D story (src/three/implant-story.js), deeper than the home page's four steps.
    story3d: 'implant',
    story: {
      title: 'Your implant, step by step',
      length: '760vh',
      marks: [0, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857],
      steps: [
        { title: 'Check-up and X-ray', text: 'The dentist examines the gap and takes an X-ray to see how much bone there is, and where nerves and sinuses lie.' },
        { title: 'Planning the implant', text: "The implant's position, angle and size are planned on the X-ray, so it sits safely in the bone and lines up with your bite." },
        { title: 'Placing the implant', text: 'With the area numbed, the titanium implant is placed in the jawbone. Most people feel pressure rather than pain.' },
        { title: 'Healing', text: "Over roughly three to six months, the bone grows tightly around the implant's threads. This bond is what makes it strong." },
        { title: 'The abutment', text: 'A small connector is fitted on top of the implant. It rises through the gum to hold the new tooth.' },
        { title: 'A crown that matches', text: 'The crown is made in a shade chosen to match your own teeth, then fixed onto the abutment.' },
        { title: 'Bite check and follow-up', text: 'The dentist checks how your teeth meet and fine-tunes the crown if needed. Regular check-ups keep the implant healthy.' },
      ],
    },
    // Each type opens into a 3D model that comes apart (src/three/implant-types.js).
    options: {
      title: 'Ways an implant can replace teeth',
      items: [
        {
          name: 'Single-tooth implant', model: 'single',
          text: 'One implant and one crown replace a single missing tooth, without filing down the teeth on either side.',
          parts: ['Crown', 'Abutment', 'Implant'],
          detail: {
            what: 'An implant takes the place of the root, and a crown made for your mouth sits on top. The teeth next to the gap are left untouched.',
            bestFor: ['One missing tooth', 'Healthy neighbouring teeth you would rather not file down for a bridge'],
            involves: 'Placing the implant, a few months of healing, then the abutment and crown.',
          },
        },
        {
          name: 'Implant bridge', model: 'bridge',
          text: 'When several teeth in a row are missing, two implants can hold a bridge of three or more new teeth.',
          parts: ['Bridge of three teeth', 'Abutments', 'Two implants'],
          detail: {
            what: 'Instead of one implant for every missing tooth, two implants hold a fixed bridge. The tooth in the middle rests on the gum between them.',
            bestFor: ['Three or more missing teeth in a row', 'Fewer implants than one per tooth'],
            involves: 'Placing two implants, healing, then fitting the bridge.',
          },
        },
        {
          name: 'Implant-supported denture', model: 'overdenture',
          text: 'For a jaw with no teeth, a few implants hold a full denture firmly, so it does not slip when you eat or speak.',
          parts: ['Removable denture', 'Clip-on attachments', 'Implants'],
          detail: {
            what: 'A full denture clips onto two to four implants. It stays firmly in place when you eat and speak, and you can still take it out to clean it.',
            bestFor: ['No teeth in a jaw', 'A denture that is loose or slips'],
            involves: 'Placing the implants, healing, then a denture made with clips that fit the attachments.',
          },
        },
        {
          name: 'All-on-X full arch', model: 'allonx',
          text: 'A full arch of fixed teeth held by four to six implants. Only the dentist removes it.',
          parts: ['Fixed full-arch bridge', 'Back implants angled', 'Four to six implants'],
          detail: {
            what: 'A complete arch of teeth is fixed onto four to six implants. The back implants are often angled to make the most of the bone, so a bone graft may not be needed.',
            bestFor: ['No teeth, or failing teeth, across a whole jaw', 'Wanting fixed teeth rather than a denture you take out'],
            involves: 'Placing the implants, healing, then the final fixed bridge. The dentist will tell you whether a temporary bridge can be fitted while you heal.',
          },
        },
      ],
    },
    fit: {
      title: 'Is an implant right for you?',
      items: [
        'You are missing one or more teeth, from decay, gum disease or an injury.',
        'Your gums are healthy, or can be treated first.',
        'There is enough bone in your jaw to hold the implant. An X-ray shows this.',
        'You would like a fixed tooth rather than one you take out.',
      ],
      note: 'Smoking and uncontrolled diabetes can slow healing. Tell the dentist about your health and any medicines at your check-up.',
    },
    care: {
      title: 'Looking after your implant',
      items: [
        'Eat soft food on that side for the first few days.',
        'Brush and floss around the implant every day, just like a natural tooth.',
        'If you smoke, stopping helps the implant heal and last longer.',
        'Keep your follow-up visits so the dentist can check the gum and bone around it.',
      ],
    },
    faq: [
      { q: 'How long does the whole treatment take?', a: 'It usually happens in stages over a few months: placing the implant, letting the bone heal around it, then fitting the crown. The dentist will give you a timeline after checking your bone.' },
      { q: 'Does getting an implant hurt?', a: 'The area is numbed first, so you should feel pressure rather than pain. Some soreness and swelling for a few days afterwards is normal.' },
      { q: 'How long does an implant last?', a: 'With good cleaning and regular check-ups, an implant can last for many years. The crown on top may need replacing one day because of normal wear.' },
      { q: "What if I don't have enough bone?", a: 'The dentist checks the bone on an X-ray. If there is not enough, a bone graft may be needed first. You will be told if this applies to you.' },
      { q: 'Why is the price not listed?', a: 'The cost depends on how many teeth are replaced, the type of crown, and whether extra steps such as a bone graft are needed. The dentist explains your options and what each costs after your check-up, before anything starts.' },
    ],
    review: null,
    related: ['crown', 'denture', 'partial'],
  },
  {
    id: 'rct',
    slug: 'root-canal-treatment',
    tagline: 'Save an infected, painful tooth',
    name: 'Root canal treatment',
    group: 'pain',
    scene: 'rct',
    seoTitle: 'Root canal treatment in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Save an infected, painful tooth with root canal treatment at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar. See each step in 3D and book on WhatsApp.',
    lead: 'When decay or a crack lets bacteria into the soft pulp inside a tooth, it can become infected and very painful. Root canal treatment removes the infection and seals the tooth, so you keep it instead of losing it.',
    story3d: 'rct',
    story: {
      title: 'Your root canal treatment, step by step',
      length: '760vh',
      marks: [0, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857],
      steps: [
        { title: 'X-ray', text: 'An X-ray shows how far the infection has spread, including any at the tip of the root.' },
        { title: 'Numbing', text: 'The tooth and gum are numbed with local anaesthetic, so you feel pressure rather than pain.' },
        { title: 'A small opening', text: 'A small opening is made in the top of the tooth to reach the infected pulp inside.' },
        { title: 'Cleaning each canal', text: 'Fine files remove the infected pulp and shape each canal, one at a time.' },
        { title: 'Rinsing', text: 'The canals are rinsed with a disinfecting solution to wash out the remaining bacteria.' },
        { title: 'Filling and sealing', text: 'The clean canals are filled with a rubber-like material, and the opening is sealed.' },
        { title: 'A crown to protect it', text: 'A back tooth usually gets a crown to stop it cracking. With the infection gone, the area around the root can heal.' },
      ],
    },
    options: {
      title: 'After the canals are sealed',
      items: [
        {
          name: 'A filling on top', model: 'rct-filling',
          text: 'The opening in the tooth is closed with a tooth-coloured filling. This is often enough for a front tooth.',
          parts: ['Tooth-coloured filling', 'Your own tooth, kept', 'Sealed canals'],
          detail: {
            what: 'The opening in the top of the tooth is closed with a tooth-coloured filling. The sealed canals stay inside your own tooth.',
            bestFor: ['Front teeth, which take less force when you bite', 'Teeth that still have plenty of their own structure'],
            involves: 'Done at the end of the root canal treatment, or at a short visit afterwards.',
          },
        },
        {
          name: 'A crown to protect it', model: 'rct-crown', book: 'crown',
          text: 'Back teeth take the most force when you chew, so a crown is often advised to stop the treated tooth from cracking.',
          parts: ['Crown', 'Your own tooth, kept', 'Sealed canals'],
          detail: {
            what: 'A crown covers the whole top of the tooth and holds it together, so it does not crack under the force of chewing.',
            bestFor: ['Back teeth (molars and premolars)', 'Teeth that were heavily filled or broken before treatment'],
            involves: 'Shaping the tooth, a scan or impression, a temporary crown, then the final crown at a later visit.',
          },
        },
      ],
    },
    fit: {
      title: 'Signs you may need it',
      items: [
        'Toothache that throbs or wakes you at night.',
        'Pain that lingers after hot or cold food and drinks.',
        'A swollen gum, or a small pimple-like bump near a tooth.',
        'A tooth that has turned darker after a knock.',
      ],
      note: 'Only an examination, and usually an X-ray, can tell for sure. If swelling spreads to your eye or neck, or you have trouble swallowing or breathing, go to the nearest emergency department.',
    },
    care: {
      title: 'After your root canal',
      items: [
        'The tooth may feel tender for a few days. Painkillers the dentist recommends usually help.',
        'Avoid biting hard food on that tooth until the final filling or crown is in place.',
        'Brush and floss as normal.',
        'Come back for the final filling or crown, so the tooth is protected for the long term.',
      ],
    },
    faq: [
      { q: 'Does root canal treatment hurt?', a: 'The tooth is numbed with local anaesthetic first, so most patients feel pressure rather than pain. It can feel tender for a few days afterwards.' },
      { q: 'How many visits will I need?', a: 'Often one or two, depending on the tooth and how much infection there is. The dentist tells you after examining it.' },
      { q: "Wouldn't it be simpler to pull the tooth out?", a: 'Keeping your own tooth is usually better for chewing and for the teeth around it. A gap often needs an implant, bridge or denture later. The dentist will explain both choices.' },
      { q: 'Will I need a crown afterwards?', a: 'Back teeth usually do, because they take the most force when you chew and can crack after treatment. A front tooth may only need a filling.' },
    ],
    review: 0,
    related: ['crown', 'filling', 'extraction'],
  },
  {
    id: 'braces',
    slug: 'braces',
    tagline: 'Straighten crooked teeth',
    name: 'Braces',
    group: 'smile',
    scene: 'braces',
    seoTitle: 'Braces in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Straighten crowded or crooked teeth with braces at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar, for children, teens and adults. Book on WhatsApp.',
    lead: 'Braces move crowded or crooked teeth into line with small brackets and a thin wire. Straighter teeth are easier to clean, and the bite works better too.',
    story3d: 'braces',
    story: {
      title: 'Your braces, step by step',
      length: '760vh',
      marks: [0, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857],
      steps: [
        { title: 'Your plan', text: 'After a check-up and X-rays, the dentist plans where each tooth needs to move.' },
        { title: 'Brackets bonded', text: 'Small brackets are bonded to the front of each tooth, one by one. No injection is needed.' },
        { title: 'The wire', text: 'A thin wire is threaded through the brackets. It pushes the teeth gently and steadily.' },
        { title: 'Month by month', text: 'Over the months, the teeth move a little at a time towards their planned positions.' },
        { title: 'Adjustments', text: 'Every few weeks the dentist adjusts the wire, and fresh elastic ties go on.' },
        { title: 'Brackets off', text: 'When the teeth are straight, the brackets are taken off and the teeth are polished.' },
        { title: 'Your retainer', text: 'A retainer, worn as advised, keeps your teeth from drifting back.' },
      ],
    },
    options: {
      title: 'Types of braces',
      confirm: true,
      items: [
        {
          name: 'Metal braces', model: 'braces-metal',
          text: 'Strong, reliable and suited to most cases, from mild crowding to bigger bite problems.',
          parts: ['Metal brackets', 'Elastic ties', 'Wire', 'Your teeth'],
          detail: {
            what: 'Small stainless-steel brackets joined by a thin wire, held with colourful elastic ties.',
            bestFor: ['Mild to severe crowding, gaps or bite problems', 'Children, teens and adults'],
            involves: 'Brackets fitted in one visit, then adjustments every few weeks until the teeth are straight, then a retainer.',
          },
        },
        {
          name: 'Tooth-coloured braces', model: 'braces-ceramic',
          text: 'Ceramic brackets that blend in with your teeth, so they are less noticeable.',
          parts: ['Tooth-coloured brackets', 'Elastic ties', 'Wire', 'Your teeth'],
          detail: {
            what: 'They work the same way as metal braces, but the brackets are ceramic and close to the colour of your teeth.',
            bestFor: ['Teens and adults who want braces to be less visible'],
            involves: 'Brackets fitted in one visit, then adjustments every few weeks, then a retainer.',
          },
        },
        {
          name: 'Clear aligners', model: 'aligner',
          text: 'A series of thin, clear trays you can take out to eat and brush. Suited to milder cases.',
          parts: ['Clear aligner', 'Your teeth'],
          detail: {
            what: 'A series of thin, clear trays made for your teeth. Each set moves the teeth a little, and you change to the next set as advised.',
            bestFor: ['Milder crowding or gaps', 'People who want to take them out to eat and brush'],
            involves: 'Wearing the trays most of the day and night, changing to the next set as advised, with regular check-ups.',
          },
        },
      ],
    },
    fit: {
      title: 'Who braces can help',
      items: [
        'Crowded, overlapping or crooked teeth.',
        'Gaps between teeth.',
        'A bite where the top and bottom teeth do not meet well.',
        'Children, teens and adults. Children are often treated while the jaw is still growing.',
      ],
      note: 'Teeth and gums need to be healthy before braces go on, so any fillings or gum treatment are done first.',
    },
    care: {
      title: 'Living with braces',
      items: [
        'Brush carefully after meals, around every bracket.',
        'Avoid hard and sticky food that can break a bracket, such as hard sweets, nuts and chewing gum.',
        'If a bracket or wire rubs, a little orthodontic wax helps until your next visit.',
        'Wear your retainer as advised once the braces come off.',
      ],
    },
    faq: [
      { q: 'How long will I wear braces?', a: 'Most people wear them for one to two years. It depends on how much the teeth need to move. You get an estimate after the check-up.' },
      { q: 'Do braces hurt?', a: 'Teeth can feel sore for a few days after the braces go on and after each adjustment. This settles, and ordinary painkillers help.' },
      { q: 'Am I too old for braces?', a: 'No. Adults can have braces too, as long as their teeth and gums are healthy.' },
      { q: 'How often do I need to visit?', a: 'Usually every few weeks, so the dentist can adjust the wire and check progress.' },
      { q: 'What happens when the braces come off?', a: 'You wear a retainer, as advised, to stop the teeth from moving back.' },
    ],
    review: null,
    related: ['whitening', 'veneer', 'filling'],
  },
  {
    id: 'crown',
    slug: 'dental-crowns',
    tagline: 'Protect a weak or broken tooth',
    name: 'Crowns',
    group: 'pain',
    scene: 'restore',
    seoTitle: 'Dental crowns in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Protect a cracked, broken or heavily filled tooth with a dental crown at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar. See how a crown is made and fitted, and book on WhatsApp.',
    lead: 'A crown is a tooth-shaped cap that covers the whole visible part of a tooth. It holds a weak, cracked or heavily filled tooth together, and is made in a shade that matches your other teeth.',
    story3d: 'crown',
    story: {
      title: 'Your crown, step by step',
      length: '760vh',
      marks: [0, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857],
      steps: [
        { title: 'Check-up', text: 'The dentist examines the tooth and may take an X-ray, to make sure the root and gum are healthy enough for a crown.' },
        { title: 'Shaping the tooth', text: 'With the tooth numbed, the old filling and weak parts are removed, and the tooth is shaped a little smaller to make room for the crown.' },
        { title: 'An exact copy', text: 'An impression or scan of the shaped tooth is taken, so the crown can be made to fit it and your bite.' },
        { title: 'A temporary crown', text: 'A temporary crown protects the tooth while your crown is being made.' },
        { title: 'Your crown is made', text: 'The crown is made to fit, in a shade chosen to match the teeth beside it.' },
        { title: 'Fitted', text: 'At the next visit the temporary crown comes off, and your crown is fixed in place with dental cement.' },
        { title: 'Bite check', text: 'The dentist checks how your teeth meet and adjusts the crown if needed, so it feels like your own tooth.' },
      ],
    },
    options: {
      title: 'Types of crowns',
      confirm: true,
      items: [
        {
          name: 'All-ceramic crown', model: 'crown-ceramic',
          text: 'Natural-looking and lets light through like real enamel. A good choice for front teeth.',
          parts: ['All-ceramic crown', 'Your tooth, shaped'],
          detail: {
            what: 'A crown made entirely of ceramic, such as E.max. It lets light through much like a natural tooth, so it blends in well.',
            bestFor: ['Front teeth, where looks matter most', 'People who prefer no metal'],
            involves: 'Usually two visits: shaping the tooth and taking an impression, with a temporary crown in between, then fitting.',
          },
        },
        {
          name: 'Zirconia crown', model: 'crown-zirconia',
          text: 'Very strong and tooth-coloured. Suited to back teeth that take the most chewing force.',
          parts: ['Tooth-coloured outer layer', 'Zirconia base, very strong', 'Your tooth, shaped'],
          detail: {
            what: 'A crown built on zirconia, a very strong white ceramic, usually finished with a tooth-coloured layer.',
            bestFor: ['Back teeth, which take the most chewing force', 'People who prefer no metal'],
            involves: 'Usually two visits: shaping the tooth and taking an impression, with a temporary crown in between, then fitting.',
          },
        },
        {
          name: 'Porcelain fused to metal', model: 'crown-pfm',
          text: 'A metal base covered in tooth-coloured porcelain. Strong, and used for many years.',
          parts: ['Porcelain layer', 'Metal base', 'Your tooth, shaped'],
          detail: {
            what: 'A metal base covered with tooth-coloured porcelain. Over time, a thin grey line can sometimes show where the crown meets the gum.',
            bestFor: ['Back teeth', 'When a strong, long-proven option is preferred'],
            involves: 'Usually two visits: shaping the tooth and taking an impression, with a temporary crown in between, then fitting.',
          },
        },
      ],
    },
    fit: {
      title: 'When a crown helps',
      items: [
        'A tooth that is cracked or broken.',
        'A tooth with a large filling that is weakening it.',
        'A back tooth after root canal treatment.',
        'A badly worn or misshapen tooth.',
        'On top of a dental implant, to replace a missing tooth.',
      ],
      note: 'If a tooth only has a small cavity, a filling is usually enough. The dentist will tell you which you need.',
    },
    care: {
      title: 'Looking after your crown',
      items: [
        'Brush twice a day and clean between your teeth, especially where the crown meets the gum.',
        'Avoid biting very hard things on the crown, such as ice, bones or hard nuts.',
        'If you grind your teeth at night, ask about a night guard.',
        'Keep your regular check-ups, so the crown and the tooth under it stay healthy.',
      ],
    },
    faq: [
      { q: 'How many visits does a crown take?', a: 'Usually two: one to shape the tooth and take an impression, and one to fit the crown. The dentist tells you after the check-up.' },
      { q: 'Does getting a crown hurt?', a: 'The tooth is numbed while it is shaped, so most people feel only pressure. It can feel a little sensitive for a few days afterwards.' },
      { q: 'How long does a crown last?', a: 'With good care, crowns often last many years. Brushing, cleaning between your teeth and regular check-ups help it last.' },
      { q: 'Will it look like my other teeth?', a: 'Yes. The shade is chosen to match the teeth beside it, so a tooth-coloured crown looks natural.' },
      { q: 'Why is the price not listed?', a: 'It depends on the type of crown and what the tooth needs first. The dentist explains your options and what each costs after your check-up, before anything starts.' },
    ],
    review: null,
    related: ['rct', 'veneer', 'implant'],
  },
  {
    id: 'veneer',
    slug: 'veneers',
    tagline: 'Fix chips, stains and small gaps',
    name: 'Veneers',
    group: 'smile',
    scene: 'studio',
    seoTitle: 'Veneers in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Fix chipped, stained or slightly uneven front teeth with porcelain or composite veneers at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar. Book on WhatsApp.',
    lead: 'A veneer is a thin, tooth-coloured shell bonded to the front of a tooth. Veneers cover chips, stains and small gaps, and can change the shape or length of your front teeth.',
    story3d: 'veneer',
    story: {
      title: 'Your veneers, step by step',
      length: '660vh',
      marks: [0, 0.167, 0.333, 0.5, 0.667, 0.833],
      steps: [
        { title: 'Your smile today', text: 'The dentist looks at your front teeth and gums, and talks with you about what you would like to change.' },
        { title: 'Planning your smile', text: 'The shape, length and shade of the new veneers are planned with you, so you know what to expect.' },
        { title: 'Preparing the teeth', text: 'For porcelain veneers, a very thin layer is polished from the front of each tooth so the veneer sits flush. Composite veneers often need little or none.' },
        { title: 'Shade and making', text: 'A shade is chosen to suit your smile, and the veneers are made to fit your teeth.' },
        { title: 'Bonded in place', text: 'Each veneer is bonded to its tooth and set hard with a blue light.' },
        { title: 'Your new smile', text: 'The dentist checks your bite and polishes the edges. Look after them like your own teeth.' },
      ],
    },
    options: {
      title: 'Types of veneers',
      confirm: true,
      items: [
        {
          name: 'Porcelain veneers', model: 'veneer-porcelain',
          text: 'Thin porcelain shells made to fit your teeth. They resist stains and keep their shine.',
          parts: ['Porcelain veneers', 'Thin bonding layer', 'Your teeth'],
          detail: {
            what: 'Thin porcelain shells, made to fit, then bonded to the front of the teeth.',
            bestFor: ['Stained or discoloured front teeth', 'Changing the shape or length of teeth', 'A long-lasting result'],
            involves: 'Usually two visits: preparing the teeth and taking an impression, then bonding the veneers.',
          },
        },
        {
          name: 'Composite veneers', model: 'veneer-composite',
          text: 'Tooth-coloured material built up in layers on the tooth, then shaped and polished.',
          parts: ['Final layer, shaped and polished', 'First composite layer', 'Your teeth'],
          detail: {
            what: 'Tooth-coloured composite, the same kind of material as a white filling, built up and shaped directly on the tooth.',
            bestFor: ['Small chips and gaps', 'A quicker option, often in one visit'],
            involves: 'Often one visit, with little or no shaping of the tooth. They may need polishing or touch-ups over the years.',
          },
        },
      ],
    },
    fit: {
      title: 'Who veneers can help',
      items: [
        'Chipped or worn front teeth.',
        'Stains that whitening cannot lift.',
        'Small gaps between the front teeth.',
        'Teeth that are slightly uneven, small or misshapen.',
      ],
      note: 'Decay and gum problems are treated first. Very crooked teeth may be better straightened with braces.',
    },
    care: {
      title: 'Looking after your veneers',
      items: [
        'Brush twice a day and clean between your teeth.',
        'Avoid biting hard things with your front teeth, such as ice, pens or hard sweets.',
        'If you grind your teeth, ask about a night guard.',
        'Keep your regular check-ups.',
      ],
    },
    faq: [
      { q: 'Do veneers damage my teeth?', a: 'Porcelain veneers need a very thin layer polished off the front of the tooth, and this cannot be put back. Composite veneers often need little or none. The dentist explains this before you decide.' },
      { q: 'Does it hurt?', a: 'Most people feel little or no discomfort. The teeth can be numbed if they need shaping.' },
      { q: 'How long do veneers last?', a: 'Porcelain veneers often last many years with good care. Composite veneers may need polishing or repair sooner.' },
      { q: 'Can veneers be whitened later?', a: 'No, veneers keep their shade. If you want whiter teeth, whitening is usually done first, and the veneer shade is chosen to match.' },
    ],
    review: null,
    related: ['whitening', 'crown', 'braces'],
  },
  {
    id: 'whitening',
    slug: 'teeth-whitening',
    tagline: 'Lift tea, coffee and smoking stains',
    name: 'Teeth whitening',
    group: 'smile',
    scene: 'studio',
    seoTitle: 'Teeth whitening in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Lift tea, coffee and smoking stains with supervised teeth whitening at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar. Book on WhatsApp.',
    lead: 'Whitening lifts stains from tea, coffee, smoking and age, so your teeth look lighter and brighter. It is done under the dentist\'s care, with your gums protected.',
    story3d: 'whitening',
    story: {
      title: 'Your whitening, step by step',
      length: '660vh',
      marks: [0, 0.167, 0.333, 0.5, 0.667, 0.833],
      steps: [
        { title: 'Shade check', text: 'The dentist checks your teeth and gums, and notes your shade today against a shade guide.' },
        { title: 'Gums protected', text: 'A protective barrier is painted along your gums, so the gel only touches your teeth.' },
        { title: 'Whitening gel', text: 'Whitening gel is applied to the front of each tooth.' },
        { title: 'Lifting the stains', text: 'The gel works on the stains, sometimes helped by a special light.' },
        { title: 'Your result', text: 'The gel and barrier are removed, and your new shade is compared with the one you started with.' },
        { title: 'Keeping it white', text: 'Less tea, coffee and smoking, and regular cleaning, help the result last.' },
      ],
    },
    options: {
      title: 'Ways to whiten',
      confirm: true,
      items: [
        {
          name: 'In-clinic whitening', model: 'whitening-clinic',
          text: 'Done in the chair, with your gums protected and the dentist watching.',
          parts: ['Whitening gel', 'Gum barrier', 'Your teeth'],
          detail: {
            what: 'A stronger whitening gel applied by the dentist, with a barrier protecting your gums.',
            bestFor: ['A quicker result', 'People who prefer the dentist to do it all'],
            involves: 'Usually one visit. Some people need a second visit for the shade they want.',
          },
        },
        {
          name: 'Take-home whitening', model: 'whitening-home',
          text: 'Thin trays made for your teeth, worn at home with a gentle gel, as the dentist advises.',
          parts: ['Tray made for your teeth', 'Whitening gel', 'Gel to use at home', 'Your teeth'],
          detail: {
            what: 'Trays made from an impression of your teeth, used at home with a milder gel.',
            bestFor: ['A gradual result', 'Topping up whitening later'],
            involves: 'An impression for the trays, then wearing them for as long as the dentist advises, with a check-up after.',
          },
        },
      ],
    },
    fit: {
      title: 'Who whitening can help',
      items: [
        'Teeth stained by tea, coffee or smoking.',
        'Teeth that have darkened with age.',
        'Before choosing the shade for new crowns or veneers.',
      ],
      note: 'Fillings, crowns and veneers do not change colour with whitening. Your teeth and gums are checked first.',
    },
    care: {
      title: 'Keeping your teeth white',
      items: [
        'For a day or two, avoid strongly coloured food and drinks, such as tea, coffee and colas.',
        'Brush twice a day and keep up regular cleaning at the clinic.',
        'Cutting down on smoking, or stopping, helps the result last.',
        'Ask about a top-up when you feel your teeth need it.',
      ],
    },
    faq: [
      { q: 'Is whitening safe for my teeth?', a: 'Yes, when it is done or supervised by a dentist. Your teeth and gums are checked first, and your gums are protected during treatment.' },
      { q: 'Will my teeth be sensitive?', a: 'Some people feel mild sensitivity for a day or two. It goes away on its own, and a toothpaste for sensitive teeth helps.' },
      { q: 'How long does the result last?', a: 'It depends on habits such as tea, coffee and smoking. A top-up can refresh it when needed.' },
      { q: 'Will my fillings or crowns whiten too?', a: 'No. Whitening works on natural teeth only, so a visible filling or crown may need replacing to match the new shade.' },
    ],
    review: null,
    related: ['veneer', 'braces', 'crown'],
  },
  {
    id: 'filling',
    slug: 'dental-fillings',
    tagline: 'Repair a cavity',
    name: 'Fillings',
    group: 'pain',
    scene: 'restore',
    seoTitle: 'Tooth-coloured fillings in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Repair cavities with tooth-coloured fillings at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar, for children and adults. See how a filling is done and book on WhatsApp.',
    lead: 'A filling repairs a tooth with a cavity. The decay is removed and the space is filled with tooth-coloured material that blends in, so the tooth looks and works as it should.',
    story3d: 'filling',
    story: {
      title: 'Your filling, step by step',
      length: '660vh',
      marks: [0, 0.167, 0.333, 0.5, 0.667, 0.833],
      steps: [
        { title: 'Check-up and X-ray', text: 'The dentist checks the tooth and may take an X-ray. Decay often goes deeper than the spot you can see.' },
        { title: 'Numbing', text: 'The area is numbed, so you feel pressure rather than pain. Very small fillings sometimes do not need it.' },
        { title: 'Decay removed', text: 'The decay is gently removed, and the cavity is cleaned and shaped.' },
        { title: 'Filled in layers', text: 'Tooth-coloured filling material is placed in thin layers, each set hard with a blue light.' },
        { title: 'Shaped and polished', text: 'The filling is shaped to fit your bite and polished smooth.' },
        { title: 'Like your own tooth', text: 'The filling blends in with the tooth. You can eat once the numbness has worn off.' },
      ],
    },
    options: {
      title: 'Types of fillings',
      confirm: true,
      items: [
        {
          name: 'Tooth-coloured composite', model: 'filling-composite',
          text: 'The most common white filling. Built up in layers and matched to the shade of your tooth.',
          parts: ['Final layer, shaped to your bite', 'Second layer', 'First layer', 'Your tooth, cavity cleaned'],
          detail: {
            what: 'A tooth-coloured resin, placed in layers and set hard with a blue light. It bonds to the tooth.',
            bestFor: ['Front and back teeth', 'Small to medium cavities'],
            involves: 'Usually one visit: the tooth is numbed if needed, the decay removed, and the filling built up and polished.',
          },
        },
        {
          name: 'Glass ionomer', model: 'filling-gic',
          text: 'A tooth-coloured filling that releases fluoride. Often used for milk teeth and near the gum line.',
          parts: ['Glass ionomer filling', 'Releases fluoride', 'Your tooth, cavity cleaned'],
          detail: {
            what: 'A tooth-coloured filling that bonds to the tooth and slowly releases fluoride, which helps protect it.',
            bestFor: ["Children's milk teeth", 'Small cavities near the gum line'],
            involves: 'Usually one short visit.',
          },
        },
      ],
    },
    fit: {
      title: 'When a filling helps',
      items: [
        'A cavity: a hole in a tooth caused by decay.',
        'A small chip or crack.',
        'An old filling that is worn, broken or leaking.',
        'A tooth that is sensitive because of a small cavity.',
      ],
      note: 'If decay has reached the nerve, a filling is not enough and root canal treatment may be needed. The dentist will tell you after the check-up.',
    },
    care: {
      title: 'After your filling',
      items: [
        'Wait until the numbness wears off before eating, so you do not bite your cheek or tongue.',
        'Some sensitivity to cold for a few days is normal.',
        'Brush twice a day with fluoride toothpaste and clean between your teeth.',
        'Cut down on sugary snacks and drinks between meals.',
        'Keep your regular check-ups, so small cavities are found early.',
      ],
    },
    faq: [
      { q: 'Does a filling hurt?', a: 'The area is numbed first, so most people feel only pressure and vibration. Very small fillings sometimes need no numbing at all.' },
      { q: 'How long does it take?', a: 'Usually one visit. The dentist tells you how long after checking the tooth.' },
      { q: 'Can I eat afterwards?', a: 'Yes. A tooth-coloured filling is set hard straight away. Wait until the numbness wears off so you do not bite your cheek or tongue.' },
      { q: 'Can old silver fillings be replaced with white ones?', a: 'Often, yes, especially if they are worn or broken. Ask the dentist at your check-up.' },
      { q: 'Do children need fillings in milk teeth?', a: 'Often, yes. A filling stops the decay from spreading and helps keep the milk tooth until the adult tooth comes in.' },
    ],
    review: null,
    related: ['rct', 'crown', 'extraction'],
  },
  {
    id: 'extraction',
    slug: 'tooth-extraction',
    tagline: 'Remove a tooth that cannot be saved',
    name: 'Tooth extraction',
    group: 'pain',
    scene: 'rct',
    seoTitle: 'Tooth extraction in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Gentle tooth extraction, including wisdom teeth, at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar, with clear aftercare advice. Book on WhatsApp.',
    lead: 'When a tooth is too damaged or infected to save, it can be removed gently with the area numbed. You get clear aftercare advice, and the dentist talks you through ways to fill the gap.',
    story3d: 'extraction',
    story: {
      title: 'Your extraction, step by step',
      length: '660vh',
      marks: [0, 0.167, 0.333, 0.5, 0.667, 0.833],
      steps: [
        { title: 'Check-up and X-ray', text: 'The dentist examines the tooth and takes an X-ray to see its roots and the bone around them.' },
        { title: 'Numbing', text: 'The area is fully numbed. You stay awake and comfortable, and the dentist checks it is numb before starting.' },
        { title: 'Gently loosened', text: 'The tooth is gently loosened from the fibres that hold it in the bone.' },
        { title: 'Removed', text: 'Once it is loose, the tooth is lifted out. You may feel pressure, but you should not feel pain.' },
        { title: 'Healing', text: 'You bite on a gauze pad to help the area settle. Over the following weeks the socket heals and the gum closes over.' },
        { title: 'Filling the gap', text: 'Once the area has healed, an implant, a bridge or a denture can replace the tooth. The dentist explains your options.' },
      ],
    },
    options: {
      title: 'Types of extraction',
      confirm: true,
      items: [
        {
          name: 'Simple extraction', model: 'extract-simple',
          text: 'For a tooth that can be seen in the mouth. It is loosened and lifted out whole.',
          parts: ['Tooth lifted out whole', 'The socket heals over'],
          detail: {
            what: 'The tooth is loosened and removed in one piece, with the area numbed.',
            bestFor: ['A badly broken or decayed tooth that can be seen', 'A very loose tooth', 'Milk teeth that are not coming out on their own'],
            involves: 'One visit. Most people are back to normal activities the next day.',
          },
        },
        {
          name: 'Surgical extraction', model: 'extract-surgical',
          text: 'For a tooth under the gum or broken at the gum line, such as a stuck wisdom tooth.',
          parts: ['Gum gently opened', 'Wisdom tooth lying sideways', 'Stitches help it heal', 'Bone around the tooth'],
          detail: {
            what: 'The gum is gently opened to reach the tooth, which may be removed in pieces. A few stitches help the gum heal.',
            bestFor: ['Wisdom teeth stuck under the gum', 'Teeth broken at the gum line'],
            involves: 'One visit, with the area numbed. Some swelling for a few days is normal, and the stitches dissolve or are taken out.',
          },
        },
      ],
    },
    fit: {
      title: 'When a tooth may need to come out',
      items: [
        'A tooth too broken or decayed to repair.',
        'An infection that root canal treatment cannot fix.',
        'A wisdom tooth that is stuck, painful or keeps getting infected.',
        'A very loose tooth because of gum disease.',
        'To make room before braces, if the dentist advises it.',
      ],
      note: 'Keeping your own tooth is usually the first choice. The dentist explains whether a filling, crown or root canal treatment could save it.',
    },
    care: {
      title: 'After an extraction',
      items: [
        'Bite on the gauze pad for as long as the dentist advises.',
        'For the first day, do not rinse hard, spit, smoke or drink through a straw. This helps the healing clot stay in place.',
        'Eat soft food and chew on the other side for a few days.',
        'Take painkillers as advised, and call the clinic if pain or swelling gets worse after a few days.',
      ],
    },
    faq: [
      { q: 'Does an extraction hurt?', a: 'The area is fully numbed, so you feel pressure but not pain. It can be sore for a few days afterwards, and ordinary painkillers usually help.' },
      { q: 'How long does healing take?', a: 'The gum usually settles within one to two weeks. The bone underneath keeps healing for a few months.' },
      { q: 'Do wisdom teeth always need to come out?', a: 'No. Only when they cause problems, such as pain, infection or damage to the tooth next to them.' },
      { q: 'Should I replace the missing tooth?', a: 'Usually, yes, especially a back tooth, so the teeth around the gap do not drift. An implant, a bridge or a denture can fill the gap.' },
    ],
    review: null,
    related: ['implant', 'partial', 'rct'],
  },
  {
    id: 'denture',
    slug: 'complete-dentures',
    tagline: 'Replace all the teeth in a jaw',
    name: 'Complete dentures',
    group: 'missing',
    scene: 'studio',
    seoTitle: 'Complete dentures in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Natural-looking complete dentures at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar, made to fit your gums and suit your smile. Book on WhatsApp.',
    lead: 'A complete denture replaces all the teeth in an upper or lower jaw. It is made to fit your gums, with teeth chosen to suit your face, so you can eat, speak and smile with confidence again.',
    story3d: 'denture',
    story: {
      title: 'Your dentures, step by step',
      length: '760vh',
      marks: [0, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857],
      steps: [
        { title: 'Your gums today', text: 'The dentist checks your gums and the bone underneath, and talks with you about how you would like your teeth to look.' },
        { title: 'Impressions', text: 'Soft impression material in a tray takes an exact copy of your gums.' },
        { title: 'Your bite', text: 'A wax rim records how your jaws meet and where your lip line sits. The size, shape and shade of the teeth are chosen with you.' },
        { title: 'Trying it in', text: 'The teeth are first set in wax, so you can see and feel the denture while changes can still be made.' },
        { title: 'Your denture is made', text: 'The wax is replaced with strong acrylic in a natural gum colour.' },
        { title: 'Fitted', text: 'The denture is fitted and adjusted so it feels comfortable. A follow-up visit lets the dentist ease any sore spots.' },
        { title: 'Looking after it', text: 'Take it out to clean every day, and at night if the dentist advises, so your gums can rest.' },
      ],
    },
    options: {
      title: 'Types of complete dentures',
      confirm: true,
      items: [
        {
          name: 'Conventional complete denture', model: 'denture-complete',
          text: 'Upper, lower or both, held in place by a close fit to your gums.',
          parts: ['Upper denture', 'Lower denture', 'Gum-coloured acrylic base'],
          detail: {
            what: 'Teeth set on a gum-coloured acrylic base, made to fit closely over your gums. An upper denture also covers the roof of the mouth.',
            bestFor: ['No teeth left in a jaw', 'A removable way to restore a full smile'],
            involves: 'Several visits: impressions, a bite record, a try-in, the fitting and a follow-up.',
          },
        },
        {
          name: 'Implant-supported denture', model: 'overdenture',
          text: 'A full denture that clips onto a few implants, so it does not slip when you eat or speak.',
          parts: ['Removable denture', 'Clip-on attachments', 'Implants'],
          detail: {
            what: 'A full denture clips onto two to four implants. It stays firmly in place, and you can still take it out to clean it.',
            bestFor: ['A denture that is loose or slips', 'People who want more confidence when eating'],
            involves: 'Placing the implants, healing, then a denture made with clips that fit the attachments.',
          },
        },
      ],
    },
    fit: {
      title: 'Who complete dentures can help',
      items: [
        'People who have lost all their teeth in the upper or lower jaw.',
        'People whose remaining teeth cannot be saved and need to be removed.',
        'People with an old denture that is loose, worn or uncomfortable.',
      ],
      note: 'If the gums have shrunk a lot, a denture can feel loose. Implants can help hold it firmly; ask the dentist whether they suit you.',
    },
    care: {
      title: 'Looking after your dentures',
      items: [
        'Take your dentures out and clean them every day with a soft brush. Rinse them after meals.',
        'Brush your gums and tongue gently, too.',
        'Keep them in water when they are out, so they do not dry and change shape.',
        'Handle them over a towel or a bowl of water, in case you drop them.',
        'Keep your regular check-ups. Gums change over time, and dentures may need adjusting.',
      ],
    },
    faq: [
      { q: 'How long does it take to get used to dentures?', a: 'Most people need a few weeks to get used to eating and speaking with new dentures. Start with soft food cut into small pieces.' },
      { q: 'Will they look natural?', a: 'Yes. The shape, size and shade of the teeth are chosen with you, and the base is coloured like gums.' },
      { q: 'Can I sleep with my dentures in?', a: 'The dentist usually advises taking them out at night, so your gums can rest.' },
      { q: 'What if my denture feels loose?', a: 'Gums change shape over time, so a denture can loosen. It can often be relined or adjusted, or held with implants.' },
    ],
    review: null,
    related: ['partial', 'implant', 'extraction'],
  },
  {
    id: 'partial',
    slug: 'partial-dentures',
    tagline: 'Replace a few missing teeth',
    name: 'Removable partial dentures',
    group: 'missing',
    scene: 'studio',
    seoTitle: 'Partial dentures in Peshawar | Family Dental & Aesthetic Clinic',
    description: 'Replace a few missing teeth with a removable partial denture at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar. Metal, acrylic and flexible options. Book on WhatsApp.',
    lead: 'A partial denture fills the gaps when some of your own teeth remain. Small clasps hold it on the teeth next to the gaps, and you take it out to clean it.',
    story3d: 'partial',
    story: {
      title: 'Your partial denture, step by step',
      length: '660vh',
      marks: [0, 0.167, 0.333, 0.5, 0.667, 0.833],
      steps: [
        { title: 'The gaps', text: 'The dentist checks your teeth and gums, and the gaps where teeth are missing.' },
        { title: 'Planning', text: 'New teeth are planned for each gap, and the dentist chooses which of your teeth will hold the denture.' },
        { title: 'The framework', text: 'From impressions of your teeth, a framework is made to fit. It joins the two sides and carries the clasps.' },
        { title: 'New teeth', text: 'Teeth that match your own are set on gum-coloured bases over each gap.' },
        { title: 'Fitted', text: 'The denture is fitted and adjusted. The clasps hold it gently on your teeth.' },
        { title: 'Looking after it', text: 'Take it out to clean every day, along with your own teeth, and at night if the dentist advises.' },
      ],
    },
    options: {
      title: 'Types of partial dentures',
      confirm: true,
      items: [
        {
          name: 'Metal framework', model: 'partial-metal',
          text: 'A thin, strong metal frame with clasps. It covers less of the mouth, so it feels lighter.',
          parts: ['Thin metal framework', 'Metal clasps', 'New teeth', 'Your teeth, with gaps'],
          detail: {
            what: 'A cast metal framework with gum-coloured bases and teeth. It is thin, strong and long-lasting.',
            bestFor: ['A long-term partial denture', 'People who want less coverage on the roof of the mouth'],
            involves: 'Several visits: impressions, a framework try-in, then fitting the finished denture.',
          },
        },
        {
          name: 'Acrylic partial', model: 'partial-acrylic',
          text: 'A gum-coloured acrylic plate with wire clasps. Quick to make and easy to add a tooth to later.',
          parts: ['Gum-coloured acrylic plate', 'Wire clasps', 'New teeth', 'Your teeth, with gaps'],
          detail: {
            what: 'Teeth on a gum-coloured acrylic plate, held with small wire clasps.',
            bestFor: ['A first or temporary partial denture', 'When more teeth may need replacing later'],
            involves: 'A few visits: impressions, a try-in, then fitting.',
          },
        },
        {
          name: 'Flexible partial', model: 'partial-flexible',
          text: 'A soft, flexible base with gum-coloured clasps, so no metal shows.',
          parts: ['Soft, flexible base', 'Gum-coloured clasps', 'New teeth', 'Your teeth, with gaps'],
          detail: {
            what: 'A thin, flexible material in a gum colour, with clasps that blend in with your gums.',
            bestFor: ['People who do not want metal clasps to show', 'A comfortable, lightweight fit'],
            involves: 'A few visits: impressions, a try-in, then fitting.',
          },
        },
      ],
    },
    fit: {
      title: 'Who a partial denture can help',
      items: [
        'People with one or more missing teeth who still have some of their own.',
        'Gaps on both sides of the mouth, which one denture can fill together.',
        'People who would rather not have implants or a bridge, or are waiting for them.',
      ],
      note: 'The teeth that hold the denture need to be healthy, so any fillings or gum treatment are done first.',
    },
    care: {
      title: 'Looking after your partial denture',
      items: [
        'Take it out and clean it every day with a soft brush. Rinse it after meals.',
        'Brush your own teeth well, especially the ones the clasps hold on to.',
        'Keep it in water when it is out, so it does not dry out.',
        'Do not bend the clasps yourself. If it feels loose or tight, the clinic can adjust it.',
      ],
    },
    faq: [
      { q: 'Will people see the clasps?', a: 'Clasps are placed to show as little as possible. With a flexible partial denture, the clasps are gum-coloured.' },
      { q: 'Does a partial denture harm my teeth?', a: 'Not if you keep it and your teeth clean and come for check-ups. The dentist plans the clasps to spread the load gently.' },
      { q: 'Can I eat with it?', a: 'Yes. Start with soft food while you get used to it, then build up to your usual food.' },
      { q: 'What other options are there?', a: 'Gaps can also be filled with implants or a bridge. The dentist explains the options that suit you.' },
    ],
    review: null,
    related: ['denture', 'implant', 'crown'],
  },
];

// The treatments page (treatments/index.html): the "front door" that lists all ten treatments.
// Items marked confirm: true need the clinic's confirmation before launch.
export const HUB = {
  seoTitle: 'Dental treatments in Peshawar | Family Dental & Aesthetic Clinic',
  description: 'All ten treatments at Family Dental & Aesthetic Clinic, Nasir Bagh Road, Peshawar: implants, root canal, braces, crowns, veneers, whitening, fillings, extraction and dentures, each shown step by step in 3D.',
  eyebrow: 'Ten treatments, one clinic',
  title: 'Our treatments',
  lead: "From a child's first filling to dentures for grandparents, every treatment is planned and carried out by Dr. Tabassum Ajmal. Open one to see how it works, step by step in 3D, or tell us what is wrong and we will help you choose.",
  gridTitle: 'Find your treatment',
  gridText: 'Each page shows the treatment step by step in 3D, the types on offer, who it suits, aftercare and common questions.',
  helper: {
    title: 'Not sure which one you need?',
    text: 'Tell us what is going on and we will show the treatments that usually help. The dentist confirms the right one at your check-up.',
    options: [
      { group: 'pain', label: 'Something hurts or is broken', hint: 'Fillings, root canal treatment, crowns or an extraction' },
      { group: 'missing', label: 'A tooth is missing', hint: 'Implants or dentures' },
      { group: 'smile', label: 'I want a nicer smile', hint: 'Whitening, veneers or braces' },
    ],
  },
  why: [
    { big: '5.0', label: 'on Google, from 93 reviews' },
    { big: 'Dr. Tabassum Ajmal', label: 'Dentist and prosthodontist' },
    { big: 'Every age', label: 'From first check-ups to dentures' },
    { big: 'Costs first', label: 'Explained before any treatment starts' },
  ],
  safety: {
    title: 'Your safety comes first',
    text: 'Careful, clean care at every visit, for every patient.',
    confirm: true,
    items: [
      { icon: 'steam', title: 'Sterilised instruments', text: 'Reusable instruments are cleaned and sterilised in an autoclave before each patient.' },
      { icon: 'glove', title: 'Single-use where possible', text: 'Needles, gloves, masks, cups and suction tips are used once, then thrown away.' },
      { icon: 'spark', title: 'Clean surfaces', text: 'The dental chair and work surfaces are disinfected between patients.' },
      { icon: 'shield', title: 'Protective wear', text: 'The dentist and assistant wear gloves, masks and eye protection.' },
    ],
  },
  faq: [
    { q: 'How do I know which treatment I need?', a: 'Book a check-up. The dentist examines your teeth, takes an X-ray if needed, and explains your options before anything starts.' },
    { fromHome: 'Why are prices not listed on the website?' },
    { fromHome: 'Do you treat children?' },
    { fromHome: 'How do I book an appointment?' },
    { fromHome: 'What are your timings?' },
  ],
  // The two moments of each treatment's 3D story shown on its card (story progress 0..1), and framing.
  thumbs: {
    implant: { a: 0.84, b: 0.43, zoom: 0.92, y: -0.1 },
    rct: { a: 0.53, b: 0.8, zoom: 1.2 },
    braces: { a: 0.37, b: 0.58, zoom: 1.1, y: -0.05 },
    crown: { a: 0.815, b: 0.68, zoom: 1.4, y: -0.05 },
    veneer: { a: 0.76, b: 0.63, zoom: 1.2 },
    whitening: { a: 0.585, b: 0.79, zoom: 1.25 },
    filling: { a: 0.643, b: 0.1, zoom: 1.1, y: -0.22 },
    extraction: { a: 0.56, b: 0.93, zoom: 0.95, y: -0.2 },
    denture: { a: 0.8, b: 0.4, zoom: 1.3 },
    partial: { a: 0.78, b: 0.47, zoom: 1.05 },
  },
};
